global:
  prefix: "&7WarPlus>&f "
warzone:
  default:
    config:
      block-heads: true
      class-cmd: ""
      death-messages: true
      enabled: true
      max-health: 20
      min-teams: 1
      item-drops: false
      monument-heal: 1
      monument-heal-chance: 0.2
      remove-entities-on-reset: true
      reset-on-empty: true
team:
  default:
    config:
      default-class: ""
      econ-reward: 5
      lives: 20
      max-players: 20
      max-score: 5
      min-players: 1
      hunger: true
      place-blocks: true
      spawn-style: small
