global:
  prefix: "&7WarPlus>&f "
  database:
    enabled: false
    dialect: mysql
    server: localhost
    port: 3306
    database-name: WarPlus
    username: root
    password: root
  restore-player-location: true
  allowed-commands:
    - /help
warzone:
  default:
    config:
      block-heads: true
      can-break-blocks: true
      class-cmd: ""
      death-messages: true
      enabled: true
      max-health: 20
      min-teams: 1
      item-drops: false
      monument-heal: 1
      monument-heal-chance: 0.2
      remove-entities-on-reset: true
      reset-on-empty: true
team:
  default:
    config:
      default-class: ""
      econ-reward: 5
      lives: 20
      max-players: 20
      max-score: 5
      min-players: 1
      hunger: true
      place-blocks: true
      spawn-style: small
