name: WarPlus
main: com.github.james9909.warplus.WarPlus
api-version: 1.13
version: 0.1.0
author: james9909
softdepend: [MagicSpells, Vault, WorldEdit]
depend: []
permissions:
  warplus.admin:
    description: WarPlus admin rights.
    default: op
  warplus.player:
    description: WarPlus player rights. Can participate in warzones.
    default: true
  warplus.zonemaker:
    description: WarPlus zonemaker rights. Can create and edit warzones.
    default: op
commands:
  wp:
    description: Base command for WarPlus
    usage: The /wp command allows you to run several other subcommands. Ex -
      | /wp setup <warzone>
