name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download ktlint
      run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.32.0/ktlint
    - name: Grant execute permission for ktlint
      run: chmod +x ktlint
    - name: Build and test with Gradle
      run: ./gradlew test build
    - name: Lint kotlin files
      run: ./ktlint "src/**/*.kt"
